repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-byte-order-marker
    - id: debug-statements
    - id: detect-private-key
    - id: check-ast

- repo: local

  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--config=pyproject.toml]

    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      args: [--settings-path=pyproject.toml]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--config=.flake8]

    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [--py310-plus]

    - id: yesqa
      name: yesqa
      entry: yesqa
      language: system
      types: [python]
